---
- hosts: localhost
  become: true
  become_user: root

  tasks:
  - name: Start docker
    service: name=docker state=started

  - name: create docker image
    command: docker build -t apache:kamesh -f $DOCKER_FILE_DIR/Dockerfile $DOCKER_FILE_DIR

  - name: create tag for the image
    command: docker tag apache:kamesh kameshcmc/apache:kamesh

  - name: docker login
    command: docker login -u kameshcmc -p Kamesh123!!

  - name: docker push the new image
    command: docker push kameshcmc/apache:kamesh

