---
- hosts: localhost
  become: true
  become_user: root

  tasks:
  - name: run the image on the docker swarm after swarm created outside this playbook
    command: docker stack deploy -c kams-service.yml kams

