#version of docker compose
version: '3'
services:
  edusvc:
    image: kameshcmc/apache:kamesh
    ports:
      - 8082:80
    volumes:
      - kamsvol:/var/www/dockerContent/log
    delploy:
      replicas: 4
volumes:
  kamsvol: {}

  
  

sudo docker stack deploy -c kams-service.yml kams