#version of docker compose
version: '3'
services:
  edusvc:
    image: kameshcmc/apache:kamesh
    ports:
      - 8082:80
    volumes:
      - kamsvol:/var/www/dockerContent/log
    delploy:
      mode: replicated
      replicas: 4
volumes:
  kamsvol: {}
